(()=>{
'use strict';
const M=window.LagrangeModel,D=window.LagrangeData.systems,$=id=>document.getElementById(id),cv=$('model'),map=$('projection-map'),pi=Math.PI,blue='#62b6e9',orange='#efac62',green='#62c8a7',purple='#ba91ec';
let yaw=.5,pitch=.65,zoom=1,drag=null,request=0;const dark=()=>matchMedia('(prefers-color-scheme:dark)').matches,num=x=>new Intl.NumberFormat('ko-KR',{maximumFractionDigits:0}).format(x);
function setup(c){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);const ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.fillStyle=dark()?'#171e27':'#f4f8fd';ctx.fillRect(0,0,r.width,r.height);return{ctx,w:r.width,h:r.height};}
function base(bound,center){return{bound,center,items:[],labels:[],head:[]};}
const line=(s,pts,color,width=1,alpha=1,dash=[])=>s.items.push({kind:'line',points:pts,color,width,alpha,dash}),face=(s,pts,color,alpha=.35)=>s.items.push({kind:'face',points:pts,color,alpha});
function point(s,p,color,r=4,label=''){s.items.push({kind:'point',points:[p],color,r,alpha:1});if(label)s.labels.push({p,text:label,color});}
function circle(r,n=180){return Array.from({length:n+1},(_,i)=>[r*Math.cos(2*pi*i/n),r*Math.sin(2*pi*i/n),0]);}
function axes(s,names){const e=s.bound*.55;for(let i=0;i<3;i++){const a=s.center.slice(),b=s.center.slice();a[i]-=e;b[i]+=e;line(s,[a,b],dark()?'#64778f':'#95aac2',.7,.6);s.labels.push({p:b,text:names[i],color:dark()?'#c8d9ec':'#3c5670'});}}
const bodyData=window.LagrangeMissions,missions=bodyData.missions,pink='#e589c8',utc=t=>new Date(t*1000).toISOString().replace('T',' ').slice(0,19)+' UTC';
let missionOptionsKey='',missionCache=null;
function missionUI(){
 const key=$('trajectory').value,active=key!=='ideal';$('mission-controls').hidden=!active;$('ideal-controls').hidden=active;$('comparison-controls').hidden=!active;$('body-info').hidden=false;document.querySelector('.body-nav').hidden=false;
 for(const o of $('view').options)o.disabled=!active&&o.value==='approach';
 $('frame').querySelector('[value="rotating"]').textContent=active?($('system').value==='sun-earth'?'태양–지구 방향 회전계':'지구–달 방향 회전계'):'두 천체와 도는 회전계';
 $('frame').querySelector('[value="inertial"]').textContent=active?'태양 중심 · 고정된 황도 방향':'질량중심 관성계';
 $('view').querySelector('[value="local"]').textContent='지구 주변 · 우주선 경로';
 $('compare-ideal').disabled=Number($('point').value)>2;$('progress').parentElement.firstChild.textContent=active?'선택 구간 시간 ':'모형 시간 · 한 주기 ';
 if(!active){if($('view').value==='approach')$('view').value='point';return;}
 $('frame').querySelector('[value="inertial"]').disabled=false;$('view').querySelector('[value="global"]').disabled=false;$('view').querySelector('[value="local"]').disabled=false;
 const m=missions[key];if(missionOptionsKey!==key){missionOptionsKey=key;$('mission-window').replaceChildren(...m.windows.map(w=>{const o=document.createElement('option');o.value=w.id;o.textContent=w.label;return o;}));
  $('mission-events').replaceChildren(...m.events.map(event=>{const b=document.createElement('button');b.textContent=event.label;b.type='button';b.addEventListener('click',()=>{
   const w=m.windows.find(w=>w.id===(event.time>=m.separation?'capsule':event.label.includes('L1 진입')?'halo':event.label.includes('귀환')||event.label.includes('지구 접근')||event.label.includes('7월')?'return':event.label.includes('L2 진입')?'halo':'outbound'))||m.windows.at(-1);
   $('mission-window').value=w.id;$('view').value=['capsule','entry'].includes(w.id)?'approach':'local';$('progress').value=Math.max(0,Math.min(1,(event.time-w.start)/(w.end-w.start)));zoom=1;pause();schedule();
  });return b;}));
 }
 const w=m.windows.find(w=>w.id===$('mission-window').value),t=M.missionTime(w,Number($('progress').value));
 $('mission-period').textContent=utc(w.start)+' → '+utc(w.end)+'. '+m.quality+'.';
 [...$('mission-events').children].forEach((b,i)=>b.setAttribute('aria-pressed',String(Math.abs(t-m.events[i].time)<Math.max(1,(w.end-w.start)*.0005))));
 if($('player-description'))$('player-description').textContent='실제 경과 시간 · '+((w.end-w.start)<86400?((w.end-w.start)/3600).toFixed(2)+'시간':((w.end-w.start)/86400).toFixed(1)+'일')+' 압축';
}
function missionPhase(key,m,t){if(key==='webb')return t<m.windows.find(w=>w.id==='halo').start?{label:'지구에서 L2로 접근',color:green}:{label:'L2 주변 운동',color:orange};if(t>=m.separation)return{label:'본체 통과 · 분리 캡슐 접근',color:purple};if(t>=m.windows.find(w=>w.id==='return').start)return{label:'L1에서 L2 부근을 거쳐 귀환',color:purple};if(t>=m.windows.find(w=>w.id==='halo').start)return{label:'L1 주변 체류',color:orange};return{label:'발사 뒤 L1로 접근',color:green};}
function missionTrail(rows,m,w,frame,system){
 const a=rows.filter(row=>row[0]>=w.start&&row[0]<=w.end),lo=Math.max(w.start,rows[0][0]),hi=Math.min(w.end,rows.at(-1)[0]);if(hi<lo)return[];
 const step=Math.max(1,Math.ceil(a.length/900)),times=[lo,...a.filter((_,i)=>i%step===0).map(row=>row[0]),hi];
 return [...new Set(times)].sort((a,b)=>a-b).map(t=>({t,p:M.scenePosition(M.ephemeris(rows,t),M.ephemeris(m.sun,t),M.ephemeris(m.moon,t),system,frame)}));
}
const bodyStyle={sun:{name:'태양',color:orange,r:13},earth:{name:'지구',color:blue,r:8},moon:{name:'달',color:'#b9bfcb',r:5}};
function body(s,id,p,unit=1,suffix=''){const a=bodyStyle[id];s.items.push({kind:'body',points:[p],color:a.color,r:a.r,radius:bodyData.body_radii_km[id]/unit,alpha:1,id});s.labels.push({p,text:a.name+suffix,color:a.color,body:id});(s.bodies??={})[id]=p;}
function pairReferences(s,S,Q,li){s.refs=S.points.map(Q);s.selected=s.refs[li-1];s.refs.forEach((p,i)=>point(s,p,i===li-1?purple:green,i===li-1?5:3,'L'+(i+1)));}
function bodyDistances(s,sun,moon,note){$('body-info').textContent=`${note} 태양–지구 ${num(Math.hypot(...sun.slice(0,3)))} km · 지구–달 ${num(Math.hypot(...moon.slice(0,3)))} km。`.replace('。','.');}
function missionScene(){
 missionUI();const key=$('trajectory').value,m=missions[key],w=m.windows.find(w=>w.id===$('mission-window').value),frame=$('frame').value,system=$('system').value,S=D[system],li=Number($('point').value),t=M.missionTime(w,Number($('progress').value)),sun=M.ephemeris(m.sun,t),moon=M.ephemeris(m.moon,t),bus=M.ephemeris(m.states,t),cap=m.capsule?M.ephemeris(m.capsule,t):null,phase=missionPhase(key,m,t),Q=q=>M.scenePosition(q,sun,moon,system,frame),L=p=>M.referencePosition(p,S.mass_ratio,sun,moon,system,frame),earth=Q([0,0,0]),sunP=Q(sun),moonP=Q(moon),view=$('view').value,approach=view==='approach',solar=view==='solar'||view==='global'&&system==='sun-earth',pairLength=Math.hypot(...(system==='sun-earth'?sun:moon).slice(0,3)),lb=system==='sun-earth'?[.007,.007,.18,.2,.2]:[.12,.14,.22,.24,.24];
 const b=solar?Math.hypot(...sun.slice(0,3))*1.18:approach?(w.id==='entry'?18000:90000):view==='point'?lb[li-1]*pairLength:view==='moon'||view==='global'?Math.hypot(...moon.slice(0,3))*1.7:2.35e6,center=solar?sunP:view==='point'?L(S.points[li-1]):earth,s=base(b,center),current=Q(bus);
 axes(s,frame==='inertial'?['X','Y','Z']:system==='sun-earth'?['x · 태양 반대','y','z']:['x · 달 방향','y','z']);
 pairReferences(s,S,L,li);s.overview={bound:pairLength*1.22,center:system==='sun-earth'?sunP:earth};
 const cacheKey=key+':'+w.id+':'+frame+':'+system;if(!missionCache||missionCache.key!==cacheKey)missionCache={key:cacheKey,bus:missionTrail(m.states,m,w,frame,system),capsule:m.capsule?missionTrail(m.capsule,m,w,frame,system):[],earth:missionTrail(m.sun.map(a=>[a[0],0,0,0,0,0,0]),m,w,frame,system)};
 function trail(a,capsule=false){let previous=null;for(const row of a){if(previous){const col=capsule?pink:missionPhase(key,m,row.t).color;line(s,[previous.p,row.p],col,1.2,.27);if(previous.t<t){const next=row.t<=t?row.p:(capsule?Q(cap):current);if(next)line(s,[previous.p,next],col,2.4,.95);}}previous=row;}}
 if(solar&&frame==='inertial')line(s,missionCache.earth.map(a=>a.p),blue,1,.35);
 trail(missionCache.bus);trail(missionCache.capsule,true);
 for(const [id,p]of[['sun',sunP],['earth',earth],['moon',moonP]])body(s,id,p);
 if($('compare-ideal').checked&&S.orbits[String(li)]){const path=S.orbits[String(li)].states.filter((_,i)=>i%4===0).map(a=>L(a.slice(1,4)));line(s,path,'#cf9ae2',1.6,.75,[5,4]);s.idealOverlay=true;}
 point(s,current,phase.color,5,key==='webb'?'웹':'본체');s.spacecraft=current;s.spacecraftName=key==='webb'?'웹':'본체';s.selected=s.refs[li-1];if(cap){s.labels.at(-1).dy=-20;point(s,Q(cap),pink,5,'캡슐');s.labels.at(-1).dy=20;s.spacecraft=Q(cap);s.spacecraftName='캡슐';}
 const measure=cap||bus,z=M.scenePosition(measure,sun,moon,system,'rotating')[2];
 s.head=[`${m.name} · ${phase.label}`,utc(t)];
 $('metrics').textContent=`${cap?'캡슐':'우주선'}의 지구 중심 거리 ${num(Math.hypot(...measure.slice(0,3)))} km · 속력 ${Math.hypot(...measure.slice(3,6)).toFixed(3)} km/s. 선택한 ${system==='sun-earth'?'태양–지구':'지구–달'} L${li} · 지구에서 ${num(M.distance(L(S.points[li-1]),earth))} km (근사). 반폭 ${num(b)} km.`;
 bodyDistances(s,sun,moon,'천체 위치의 시각: '+utc(t)+'.');
 $('readout').textContent=`${frame==='rotating'?'각 날짜의 '+(system==='sun-earth'?'태양–지구':'지구–달')+' 방향에 맞춘 회전 좌표':'태양 중심 · 고정된 J2000 황도 방향'}. 초록 출발 · 주황 체류 · 보라 귀환/본체 · 분홍 캡슐. 옅은 선은 전체 구간, 진한 선은 현재까지. ${s.idealOverlay?'보라 점선은 선택점의 이상 헤일로 참조 형상. ':''}L1–L5는 현재 두 천체의 거리에 맞춘 근사 기준. ${cap?'캡슐은 대기 진입까지의 항법 예측. ':''}${w.id==='outbound'?m.coverage_note+' ':''}${$('body-size').value==='physical'?'천체 기준 반지름 비례 · 작은 천체는 중심 표식.':'천체 표식 크기는 식별용 · 중심 위치와 공간 축은 거리 비례.'}`;
 overview(s,system);return s;
}
function overview(s,system){
 const{ctx:c,w,h}=setup(map),o=s.overview,sc=Math.min(w-38,h-64)/(2*o.bound),P=p=>[w/2+(p[0]-o.center[0])*sc,(h+12)/2-(p[1]-o.center[1])*sc],ink=dark()?'#c5d6eb':'#3e5874';c.font='10px system-ui';c.fillStyle=ink;c.fillText((system==='sun-earth'?'태양–지구':'지구–달')+' · 다섯 점의 전체 배치',6,14);c.strokeStyle=dark()?'#53677e':'#a3b3c5';c.beginPath();c.moveTo(10,(h+12)/2);c.lineTo(w-10,(h+12)/2);c.stroke();
 const labels=[];function dot(p,color,r,text){const q=P(p);if(q[0]<4||q[0]>w-4||q[1]<20||q[1]>h-24)return;c.fillStyle=color;c.beginPath();c.arc(...q,r,0,2*pi);c.fill();labels.push({q,text,color});}
 s.refs?.forEach((p,i)=>dot(p,i+1===Number($('point').value)?purple:green,3,'L'+(i+1)));
 for(const[id,p]of Object.entries(s.bodies||{}))dot(p,bodyStyle[id].color,id==='sun'?5:3,bodyStyle[id].name);
 if(s.spacecraft)dot(s.spacecraft,pink,2,'우주선');
 placeLabels(c,labels,w,20,h-24,9);
 c.fillStyle=ink;c.font='9px system-ui';c.fillText('x–y 투영 · 거리 비례 · L점은 근사 기준',6,h-8);
}

function controls(){const potential=$('mode').value==='potential';document.querySelector('.body-nav').hidden=potential;$('body-info').hidden=potential;if(potential){$('frame').value='rotating';$('view').value='point';}$('frame').querySelector('[value="inertial"]').disabled=potential;$('view').querySelector('[value="global"]').disabled=potential;for(const o of $('view').options)o.disabled=potential&&o.value!=='point'||!potential&&o.value==='approach';}
function scene(){missionUI();if($('trajectory').value!=='ideal')return missionScene();if($('player-description'))$('player-description').textContent='시간 전개 · 이상 CR3BP 궤도';controls();const key=$('system').value,S=D[key],mu=S.mass_ratio,li=Number($('point').value),L=S.points[li-1],orbit=S.orbits[String(li)],f=Number($('progress').value),T=orbit?orbit.period:2*pi,t=f*T,potential=$('mode').value==='potential',inertial=$('frame').value==='inertial',local=['local','point','moon'].includes($('view').value),Q=p=>inertial?M.rotate(p,t):p;
 const bounds=key==='sun-earth'?[.007,.007,.18,.2,.2]:[.12,.14,.22,.24,.24],surfaceBounds=key==='sun-earth'?[.006,.006,.16,.2,.2]:[.12,.14,.2,.2,.2];
 const ref=bodyData.ideal_reference,rm=missions[ref.mission],rs=M.ephemeris(rm.sun,ref.time),rmoon=M.ephemeris(rm.moon,ref.time),earthBase=[key==='sun-earth'?1-mu:-mu,0,0],thirdRel=M.pairBasis(rs,rmoon,key).map(a=>a.reduce((v,x,i)=>v+x*(key==='sun-earth'?rmoon[i]:rs[i]),0)/S.lunit),third=thirdRel.map((x,i)=>x+earthBase[i]),bp={earth:Q(earthBase),sun:Q(key==='sun-earth'?[-mu,0,0]:third),moon:Q(key==='earth-moon'?[1-mu,0,0]:third)},view=$('view').value;
 const b=potential?surfaceBounds[li-1]:view==='point'?bounds[li-1]:view==='local'?2.35e6/S.lunit:view==='moon'?M.distance(bp.moon,bp.earth)*1.7:view==='solar'?M.distance(bp.sun,bp.earth)*1.18:1.4,center=potential?L:view==='point'?Q(L):view==='local'||view==='moon'?bp.earth:view==='solar'?bp.sun:[0,0,0],s=base(b,center),primary=key==='sun-earth'?'태양':'지구',secondary=key==='sun-earth'?'지구':'달';
 let q=null,current=null,trail=[];if(orbit){q=M.state(orbit,f);current=inertial?M.rotate(q,t):q.slice(0,3);trail=orbit.states.filter((_,i)=>i%3===0).map(a=>inertial?M.rotate(a.slice(1,4),a[0]):a.slice(1,4));}
 if(!potential){axes(s,['x','y','z']);if(!local){line(s,circle(1-mu),blue,1,.25);line(s,[Q([-1.15,0,0]),Q([1.25,0,0])],blue,.8,.4);line(s,[Q([-mu,0,0]),Q(S.points[3]),Q([1-mu,0,0]),Q(S.points[4]),Q([-mu,0,0])],green,.8,.3);}
  for(const[id,p]of Object.entries(bp))body(s,id,p,S.lunit,id===(key==='sun-earth'?'moon':'sun')?' · 참고':'' );
  pairReferences(s,S,Q,li);s.overview={bound:1.4,center:[0,0,0]};
  if(orbit){line(s,trail,orange,1.5,.55);const reached=orbit.states.filter((a,i)=>i%3===0&&a[0]<=t).map(a=>inertial?M.rotate(a.slice(1,4),a[0]):a.slice(1,4));line(s,[...reached,current],orange,2.6,.95);point(s,current,orange,6,'모형 위치');s.spacecraft=current;s.spacecraftName='모형 위치';if(local){const flat=trail.map(p=>[p[0],p[1],0]);line(s,flat,blue,1,.35);line(s,[current,[current[0],current[1],0]],blue,1,.65);}}
  s.head=[`${primary}–${secondary} · ${inertial?'질량중심 관성계':'두 천체와 도는 회전계'}`,orbit?`L${li} 헤일로 · ${(t*S.tunit/86400).toFixed(1)} / ${(T*S.tunit/86400).toFixed(1)}일`:`L${li} 평형점 · 계의 한 공전 주기 비교`];
 }else{
  axes(s,['Δx','Δy','ΔV_eff']);const V0=-M.potential(L,mu),N=30,grid=Array.from({length:N+1},(_,i)=>Array.from({length:N+1},(_,j)=>{const p=[L[0]-b+2*b*i/N,L[1]-b+2*b*j/N,0];if(Math.min(Math.hypot(p[0]+mu,p[1]),Math.hypot(p[0]-1+mu,p[1]))<b*.09)return null;return{p,v:-M.potential(p,mu)-V0};}));
  const max=Math.max(...grid.flat().filter(Boolean).map(a=>Math.abs(a.v))),scale=b*.65/max;
  for(let i=0;i<N;i++)for(let j=0;j<N;j++){const a=[grid[i][j],grid[i+1][j],grid[i+1][j+1],grid[i][j+1]];if(a.every(Boolean)){face(s,a.map(q=>[q.p[0],q.p[1],q.v*scale]),a.reduce((sum,q)=>sum+q.v,0)>=0?orange:blue,.38);if(i%5===0)line(s,[a[0],a[3]].map(q=>[q.p[0],q.p[1],q.v*scale]),blue,.6,.6);}}
  point(s,L,purple,6,'L'+li);if(orbit){const onSurface=p=>[p[0],p[1],(-M.potential([p[0],p[1],0],mu)-V0)*scale];line(s,trail.map(onSurface),orange,1.6,.8);point(s,onSurface(q),orange,5,'투영 위치');}s.head=[`L${li} 주변 · 회전계 퍼텐셜`,'높이 = −Ω(x,y,0) − [−Ω(L)] · 공간 z와 다름'];s.surface=`ΔV_eff 표시 범위 ±${max.toExponential(2)}. 높이 척도 ${scale.toExponential(2)} 길이단위/퍼텐셜단위.`;
 }
 const distanceEarth=key==='sun-earth'?M.distance(L,[1-mu,0,0]):M.distance(L,[-mu,0,0]),stability=li<=3?'선형 불안정':'선형 안정 (이상 모형의 작은 교란)';
 $('metrics').textContent=`L${li} · ${stability}. 지구에서 약 ${num(distanceEarth*S.lunit)} km. ${orbit?`예시 궤도 주기 ${(T*S.tunit/86400).toFixed(2)}일. ${potential?`투영 위치의 시간 ${(t*S.tunit/86400).toFixed(1)}일.`:`현재 공간 z ${num(q[2]*S.lunit)} km.`}`:'선택점에는 헤일로 궤도를 표시하지 않습니다.'} ${potential?s.surface:local?'x·y·z에 같은 길이 척도.'+(orbit?' 파랑은 z=0 투영.':''):'전체 계의 공간 척도.'+(key==='sun-earth'?' L1·L2는 지구 가까이 겹쳐 보입니다.':'')}`;
 $('readout').textContent=potential?'높이는 z=0 평면 위 유효 퍼텐셜 차입니다. '+(orbit?'주황은 궤도의 x–y 투영을 이 그래프 위에 올린 표시이며, 실제 공간 z는 아닙니다. ':'선택점의 국소 퍼텐셜은 회전계에서 시간에 따라 바뀌지 않습니다. ')+'색은 기준값보다 높은/낮은 값.':inertial?'질량중심 관성계 · 점과 천체도 함께 이동합니다. 주황 전체 선은 표시한 시간 구간의 궤적이며, 회전계에서 닫힌 헤일로도 관성계에서는 같은 모양으로 닫히지 않습니다.':orbit?'회전계 · 주황은 CR3BP 헤일로 해, 파랑은 궤도의 평면 투영. 재생은 계산된 궤도 시간이며 실제 우주선 관측 자료가 아닙니다.':'회전계에서 L1–L5는 z=0에 있는 고립된 점입니다. 관성계로 바꾸면 ‘고정’이 좌표계에 의존한다는 사실을 확인할 수 있습니다.';
 $('body-info').textContent='이상 모형 · 태양–지구 '+num(M.distance(bp.sun,bp.earth)*S.lunit)+' km · 지구–달 '+num(M.distance(bp.moon,bp.earth)*S.lunit)+' km. 세 번째 천체는 '+utc(ref.time)+' 방향·거리 참고이며 모형의 힘에 포함하지 않습니다.';if(!potential){$('readout').textContent+=' '+($('body-size').value==='physical'?'기준 반지름 비례, 작은 천체는 중심 표식.':'천체 표식 크기는 식별용.')+' '+(key==='sun-earth'?'달':'태양')+'은 기준시각의 참고 배치.';overview(s,key);}else projection(s,S,li,t,orbit,q,inertial,potential);return s;
}
function projection(scene,S,li,t,orbit,q,inertial,potential){const{ctx:c,w,h}=setup(map),b=scene.bound,center=scene.center,L=20,T=26,W=w-30,H=h-50,sc=Math.min(W,H)/(2*b),P=p=>[w/2+(p[0]-center[0])*sc,(h+T)/2-(p[1]-center[1])*sc];c.font='10px system-ui';c.fillStyle=dark()?'#c5d6eb':'#3e5874';c.fillText(potential?'공간 z=0 · 퍼텐셜 그래프의 정의역':`위에서 본 x–y 투영 · ${inertial?'관성계':'회전계'}`,6,14);c.save();c.beginPath();c.rect(8,22,w-16,h-40);c.clip();
 function dot(p,color,r){c.fillStyle=color;c.beginPath();c.arc(...P(p),r,0,2*pi);c.fill();}function path(a,color){c.strokeStyle=color;c.lineWidth=1.3;c.beginPath();a.forEach((p,i)=>i?c.lineTo(...P(p)):c.moveTo(...P(p)));c.stroke();}
 path([[center[0]-b,center[1],0],[center[0]+b,center[1],0]],dark()?'#53677e':'#a3b3c5');path([[center[0],center[1]-b,0],[center[0],center[1]+b,0]],dark()?'#53677e':'#a3b3c5');
 if(orbit&&!potential){path(orbit.states.filter((_,i)=>i%4===0).map(a=>inertial?M.rotate(a.slice(1,4),a[0]):a.slice(1,4)),orange);dot(inertial?M.rotate(q,t):q,orange,3.5);}
 S.points.forEach((p,i)=>dot(inertial?M.rotate(p,t):p,i===li-1?purple:green,i===li-1?4:2));c.restore();c.fillStyle=dark()?'#c5d6eb':'#3e5874';c.fillText(`가로·세로 같은 척도 · 반폭 ${num(b*S.lunit)} km`,6,h-8);
}
function placeLabels(c,labels,w,top,bottom,font=11){
 c.font='bold '+font+'px system-ui';const boxes=[];
 for(const a of labels){const[qx,qy]=a.q,len=c.measureText(a.text).width+8,high=font+5;let best=null,bestCost=Infinity;
  for(const dx of[a.dx??9,-len-9,18,-len-18])for(const dy of[a.dy??-12,19,-30,36,-48,53]){const x=Math.max(3,Math.min(w-len-3,qx+dx)),y=Math.max(top+high,Math.min(bottom,qy+dy)),box={x,y:y-high,w:len,h:high};const overlap=boxes.reduce((sum,b)=>sum+Math.max(0,Math.min(x+len,b.x+b.w)-Math.max(x,b.x))*Math.max(0,Math.min(y,b.y+b.h)-Math.max(y-high,b.y)),0);const cost=overlap*100+Math.abs(x-qx)+Math.abs(y-qy);if(cost<bestCost){best={box,x,y};bestCost=cost;}}
  boxes.push(best.box);c.globalAlpha=.93;c.fillStyle=dark()?'#171e27':'#f4f8fd';c.fillRect(best.box.x,best.box.y,best.box.w,best.box.h);c.globalAlpha=.7;c.strokeStyle=a.color;c.lineWidth=.7;c.setLineDash([]);c.beginPath();c.moveTo(qx,qy);c.lineTo(best.x+(qx<best.x?0:Math.min(len,qx-best.x)),best.y-4);c.stroke();c.globalAlpha=1;c.fillStyle=a.color;c.fillText(a.text,best.x+4,best.y-3);
 }
}
function render(s){const{ctx:c,w,h}=setup(cv),bottom=h-65,sc=Math.min(w-38,h-140)/(2*s.bound)*zoom,project=p=>{const v=p.map((a,i)=>a-s.center[i]),xx=Math.cos(yaw)*v[0]-Math.sin(yaw)*v[1],yy=Math.sin(yaw)*v[0]+Math.cos(yaw)*v[1],zz=Math.cos(pitch)*v[2]-Math.sin(pitch)*yy,depth=Math.sin(pitch)*v[2]+Math.cos(pitch)*yy;return[w/2+xx*sc,(53+bottom)/2-zz*sc,depth];},visible=q=>q[0]>=5&&q[0]<=w-5&&q[1]>=58&&q[1]<=bottom-5;
 const primitives=[];for(const item of s.items){if(item.kind==='line'&&!item.dash?.length){for(let i=0;i<item.points.length-1;i++)primitives.push({...item,projected:[project(item.points[i]),project(item.points[i+1])]});}else primitives.push({...item,projected:item.points.map(project)});}for(const p of primitives)p.depth=p.projected.reduce((a,q)=>a+q[2],0)/p.projected.length;primitives.sort((a,b)=>b.depth-a.depth);c.save();c.beginPath();c.rect(0,53,w,Math.max(1,bottom-53));c.clip();
 for(const p of primitives){c.globalAlpha=p.alpha;c.strokeStyle=p.color;c.fillStyle=p.color;c.lineWidth=p.width||.5;c.setLineDash(p.dash||[]);c.beginPath();if(p.kind==='point'){c.arc(p.projected[0][0],p.projected[0][1],p.r,0,2*pi);c.fill();}else if(p.kind==='body'){const q=p.projected[0],physical=$('body-size').value==='physical',r=physical?Math.max(.8,p.radius*sc):Math.max(p.r,p.radius*sc);if(r>1.5){const g=c.createRadialGradient(q[0]-r*.3,q[1]-r*.3,r*.1,q[0],q[1],r);g.addColorStop(0,p.id==='sun'?'#ffe1a1':p.id==='earth'?'#acdfff':'#f5f6fa');g.addColorStop(.55,p.color);g.addColorStop(1,p.id==='sun'?'#b86a20':p.id==='earth'?'#20588a':'#59616d');c.fillStyle=g;}c.arc(q[0],q[1],r,0,2*pi);c.fill();c.fillStyle=p.id==='sun'?'#fff3c0':'#eef7ff';c.fillRect(q[0]-1,q[1]-1,2,2);}else{p.projected.forEach((q,i)=>i?c.lineTo(q[0],q[1]):c.moveTo(q[0],q[1]));if(p.kind==='face'){c.closePath();c.fill();}else c.stroke();}}
 c.setLineDash([]);c.globalAlpha=1;const labels=s.labels.map(a=>({...a,q:project(a.p)})).filter(a=>visible(a.q));c.restore();
 const edgeLabels=[];for(const[id,p]of Object.entries(s.bodies||{})){const q=project(p),inside=visible(q),button=$('locate-'+id);button.querySelector('span').textContent=inside?'●':'↗';button.dataset.visible=String(inside);button.title=bodyStyle[id].name+(inside?' · 중심 위치가 시야 안':' · 시야 밖, 눌러 이동');if(!inside){const dx=q[0]-w/2,dy=q[1]-(53+bottom)/2,fx=(w/2-12)/(Math.abs(dx)||1),fy=(bottom-53-26)/2/(Math.abs(dy)||1),f=Math.min(fx,fy),x=w/2+dx*f,y=(53+bottom)/2+dy*f;edgeLabels.push({q:[x,y],text:bodyStyle[id].name+' · 시야 밖',color:bodyStyle[id].color});c.fillStyle=bodyStyle[id].color;c.beginPath();const ang=Math.atan2(dy,dx);c.moveTo(x,y);c.lineTo(x-8*Math.cos(ang-.5),y-8*Math.sin(ang-.5));c.lineTo(x-8*Math.cos(ang+.5),y-8*Math.sin(ang+.5));c.closePath();c.fill();}}
 for(const [p,name,color]of[[s.spacecraft,s.spacecraftName,pink],[s.selected,'선택 L'+$('point').value,purple]]){if(!p)continue;const q=project(p);if(visible(q))continue;const dx=q[0]-w/2,dy=q[1]-(53+bottom)/2,f=Math.min((w/2-12)/(Math.abs(dx)||1),(bottom-53-26)/2/(Math.abs(dy)||1)),x=w/2+dx*f,y=(53+bottom)/2+dy*f;edgeLabels.push({q:[x,y],text:name+' · 시야 밖',color});}
 placeLabels(c,[...labels,...edgeLabels],w,54,bottom-3);c.fillStyle=dark()?'#dfebfb':'#29425f';c.font='bold 11px system-ui';s.head.forEach((text,i)=>c.fillText(text,8,18+17*i,w-95));c.font='10px system-ui';c.fillText(`드래그/방향키 회전 · +− 배율 ${zoom.toFixed(2)}×`,8,h-8);$('zoom-info').textContent=zoom.toFixed(2)+'×';$('progress-value').textContent=(Number($('progress').value)*100).toFixed(1)+'%';
}

function schedule(){if(!request)request=requestAnimationFrame(()=>{request=0;render(scene());});}function pause(){$('progress').dispatchEvent(new Event('input',{bubbles:true}));}
for(const el of document.querySelectorAll('.controls input,.controls select'))el.addEventListener('input',()=>{if(['trajectory','mission-window'].includes(el.id)){if(el.id==='trajectory'&&el.value!=='ideal')$('point').value=el.value==='genesis'?'1':'2';missionUI();$('progress').value=0;$('view').value=$('trajectory').value==='ideal'?'point':['capsule','entry'].includes($('mission-window').value)?'approach':'local';zoom=1;pause();}if(['system','point'].includes(el.id)){if($('trajectory').value==='ideal')$('progress').value=0;if(el.id==='point')$('view').value='point';zoom=1;pause();}if(el.id==='view')zoom=1;schedule();});
$('reset').addEventListener('click',()=>{$('trajectory').value='webb';missionOptionsKey='';missionUI();$('system').value='sun-earth';$('point').value='2';$('view').value='local';$('mode').value='space';$('frame').value='rotating';$('body-size').value='symbol';$('compare-ideal').checked=true;$('progress').value=0;yaw=.5;pitch=.65;zoom=1;pause();schedule();});
for(const[id,view]of[['sun','solar'],['earth','local'],['moon','moon']])$('locate-'+id).addEventListener('click',()=>{if($('trajectory').value==='ideal')$('mode').value='space';$('view').value=view;zoom=1;yaw=0;pitch=-pi/2;pause();schedule();});
$('front').addEventListener('click',()=>{yaw=0;pitch=-pi/2;pause();schedule();});$('oblique').addEventListener('click',()=>{yaw=.5;pitch=.65;pause();schedule();});
cv.addEventListener('pointerdown',e=>{drag=[e.clientX,e.clientY];cv.setPointerCapture(e.pointerId);pause();});cv.addEventListener('pointerup',()=>drag=null);cv.addEventListener('pointercancel',()=>drag=null);cv.addEventListener('pointermove',e=>{if(!drag)return;yaw+=(e.clientX-drag[0])*.009;pitch=Math.max(-1.57,Math.min(1.57,pitch+(e.clientY-drag[1])*.009));drag=[e.clientX,e.clientY];schedule();});cv.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.35,Math.min(4,zoom*Math.exp(-e.deltaY*.001)));pause();schedule();},{passive:false});
cv.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')yaw-=.1;if(e.key==='ArrowRight')yaw+=.1;if(e.key==='ArrowUp')pitch=Math.min(1.57,pitch+.1);if(e.key==='ArrowDown')pitch=Math.max(-1.57,pitch-.1);if(e.key==='+')zoom=Math.min(4,zoom*1.2);if(e.key==='-')zoom=Math.max(.35,zoom/1.2);pause();schedule();});
$('show-controls').addEventListener('click',()=>{document.body.dataset.controlsVisible='true';$('controls').scrollIntoView({block:'start'});$('back-model').focus({preventScroll:true});});$('back-model').addEventListener('click',()=>{document.body.scrollTop=0;document.body.dataset.controlsVisible='false';cv.focus({preventScroll:true});});document.body.addEventListener('scroll',()=>{if(document.body.scrollTop<20)document.body.dataset.controlsVisible='false';});new ResizeObserver(schedule).observe(cv);new ResizeObserver(schedule).observe(map);matchMedia('(prefers-color-scheme:dark)').addEventListener('change',schedule);schedule();
})();
