(()=>{
'use strict';
const M=window.LagrangeModel,D=window.LagrangeData.systems,$=id=>document.getElementById(id),cv=$('model'),map=$('projection-map'),pi=Math.PI,blue='#62b6e9',orange='#efac62',green='#62c8a7',purple='#ba91ec';
let yaw=.5,pitch=.65,zoom=1,drag=null,request=0;const dark=()=>matchMedia('(prefers-color-scheme:dark)').matches,num=x=>new Intl.NumberFormat('ko-KR',{maximumFractionDigits:0}).format(x);
function setup(c){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);const ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.fillStyle=dark()?'#171e27':'#f4f8fd';ctx.fillRect(0,0,r.width,r.height);return{ctx,w:r.width,h:r.height};}
function base(bound,center){return{bound,center,items:[],labels:[],head:[]};}
const line=(s,pts,color,width=1,alpha=1)=>s.items.push({kind:'line',points:pts,color,width,alpha}),face=(s,pts,color,alpha=.35)=>s.items.push({kind:'face',points:pts,color,alpha});
function point(s,p,color,r=4,label=''){s.items.push({kind:'point',points:[p],color,r,alpha:1});if(label)s.labels.push({p,text:label,color});}
function circle(r,n=180){return Array.from({length:n+1},(_,i)=>[r*Math.cos(2*pi*i/n),r*Math.sin(2*pi*i/n),0]);}
function axes(s,names){const e=s.bound*.55;for(let i=0;i<3;i++){const a=s.center.slice(),b=s.center.slice();a[i]-=e;b[i]+=e;line(s,[a,b],dark()?'#64778f':'#95aac2',.7,.6);s.labels.push({p:b,text:names[i],color:dark()?'#c8d9ec':'#3c5670'});}}
function controls(){const potential=$('mode').value==='potential';if(potential){$('frame').value='rotating';$('view').value='local';}if($('frame').value==='inertial')$('view').value='global';$('frame').querySelector('[value="inertial"]').disabled=potential;$('view').querySelector('[value="global"]').disabled=potential;$('view').querySelector('[value="local"]').disabled=$('frame').value==='inertial';}
function scene(){controls();const key=$('system').value,S=D[key],mu=S.mass_ratio,li=Number($('point').value),L=S.points[li-1],orbit=S.orbits[String(li)],f=Number($('progress').value),T=orbit?orbit.period:2*pi,t=f*T,potential=$('mode').value==='potential',inertial=$('frame').value==='inertial',local=$('view').value==='local',Q=p=>inertial?M.rotate(p,t):p;
 const bounds=key==='sun-earth'?[.007,.007,.18,.2,.2]:[.12,.14,.22,.24,.24],surfaceBounds=key==='sun-earth'?[.006,.006,.16,.2,.2]:[.12,.14,.2,.2,.2];
 const b=local?(potential?surfaceBounds[li-1]:bounds[li-1]):1.4,center=local?L:[0,0,0],s=base(b,center),primary=key==='sun-earth'?'태양':'지구',secondary=key==='sun-earth'?'지구':'달';
 let q=null,current=null,trail=[];if(orbit){q=M.state(orbit,f);current=inertial?M.rotate(q,t):q.slice(0,3);trail=orbit.states.filter((_,i)=>i%3===0).map(a=>inertial?M.rotate(a.slice(1,4),a[0]):a.slice(1,4));}
 if(!potential){axes(s,['x','y','z']);if(!local){line(s,circle(1-mu),blue,1,.25);line(s,[Q([-1.15,0,0]),Q([1.25,0,0])],blue,.8,.4);line(s,[Q([-mu,0,0]),Q(S.points[3]),Q([1-mu,0,0]),Q(S.points[4]),Q([-mu,0,0])],green,.8,.3);}
  const p1=Q([-mu,0,0]),p2=Q([1-mu,0,0]);for(const[p,label,color,r]of[[p1,primary,orange,9],[p2,secondary,blue,6]])if(M.distance(p,center)<b*1.7)point(s,p,color,r,label);
  S.points.forEach((p,i)=>{const v=Q(p);if(M.distance(v,center)<b*1.7)point(s,v,i===li-1?purple:green,i===li-1?5:3,i===li-1||i>=2||key==='earth-moon'?'L'+(i+1):'');});
  if(orbit){line(s,trail,orange,1.5,.55);const reached=orbit.states.filter((a,i)=>i%3===0&&a[0]<=t).map(a=>inertial?M.rotate(a.slice(1,4),a[0]):a.slice(1,4));line(s,[...reached,current],orange,2.6,.95);point(s,current,orange,6,'모형 위치');if(local){const flat=trail.map(p=>[p[0],p[1],0]);line(s,flat,blue,1,.35);line(s,[current,[current[0],current[1],0]],blue,1,.65);}}
  s.head=[`${primary}–${secondary} · ${inertial?'질량중심 관성계':'두 천체와 도는 회전계'}`,orbit?`L${li} 헤일로 · ${(t*S.tunit/86400).toFixed(1)} / ${(T*S.tunit/86400).toFixed(1)}일`:`L${li} 평형점 · 계의 한 공전 주기 비교`];
 }else{
  axes(s,['Δx','Δy','ΔV_eff']);const V0=-M.potential(L,mu),N=30,grid=Array.from({length:N+1},(_,i)=>Array.from({length:N+1},(_,j)=>{const p=[L[0]-b+2*b*i/N,L[1]-b+2*b*j/N,0];if(Math.min(Math.hypot(p[0]+mu,p[1]),Math.hypot(p[0]-1+mu,p[1]))<b*.09)return null;return{p,v:-M.potential(p,mu)-V0};}));
  const max=Math.max(...grid.flat().filter(Boolean).map(a=>Math.abs(a.v))),scale=b*.65/max;
  for(let i=0;i<N;i++)for(let j=0;j<N;j++){const a=[grid[i][j],grid[i+1][j],grid[i+1][j+1],grid[i][j+1]];if(a.every(Boolean)){face(s,a.map(q=>[q.p[0],q.p[1],q.v*scale]),a.reduce((sum,q)=>sum+q.v,0)>=0?orange:blue,.38);if(i%5===0)line(s,[a[0],a[3]].map(q=>[q.p[0],q.p[1],q.v*scale]),blue,.6,.6);}}
  point(s,L,purple,6,'L'+li);if(orbit){const onSurface=p=>[p[0],p[1],(-M.potential([p[0],p[1],0],mu)-V0)*scale];line(s,trail.map(onSurface),orange,1.6,.8);point(s,onSurface(q),orange,5,'투영 위치');}s.head=[`L${li} 주변 · 회전계 퍼텐셜`,'높이 = −Ω(x,y,0) − [−Ω(L)] · 공간 z와 다름'];s.surface=`ΔV_eff 표시 범위 ±${max.toExponential(2)}. 높이 척도 ${scale.toExponential(2)} 길이단위/퍼텐셜단위.`;
 }
 const distanceEarth=key==='sun-earth'?M.distance(L,[1-mu,0,0]):M.distance(L,[-mu,0,0]),stability=li<=3?'선형 불안정':'선형 안정 (이상 모형의 작은 교란)';
 $('metrics').textContent=`L${li} · ${stability}. 지구에서 약 ${num(distanceEarth*S.lunit)} km. ${orbit?`예시 궤도 주기 ${(T*S.tunit/86400).toFixed(2)}일. ${potential?`투영 위치의 시간 ${(t*S.tunit/86400).toFixed(1)}일.`:`현재 공간 z ${num(q[2]*S.lunit)} km.`}`:'선택점에는 헤일로 궤도를 표시하지 않습니다.'} ${potential?s.surface:local?'x·y·z에 같은 길이 척도.'+(orbit?' 파랑은 z=0 투영.':''):'전체 계의 공간 척도.'+(key==='sun-earth'?' L1·L2는 지구 가까이 겹쳐 보입니다.':'')}`;
 $('readout').textContent=potential?'높이는 z=0 평면 위 유효 퍼텐셜 차입니다. '+(orbit?'주황은 궤도의 x–y 투영을 이 그래프 위에 올린 표시이며, 실제 공간 z는 아닙니다. ':'선택점의 국소 퍼텐셜은 회전계에서 시간에 따라 바뀌지 않습니다. ')+'색은 기준값보다 높은/낮은 값.':inertial?'질량중심 관성계 · 점과 천체도 함께 이동합니다. 주황 전체 선은 표시한 시간 구간의 궤적이며, 회전계에서 닫힌 헤일로도 관성계에서는 같은 모양으로 닫히지 않습니다.':orbit?'회전계 · 주황은 CR3BP 헤일로 해, 파랑은 궤도의 평면 투영. 재생은 계산된 궤도 시간이며 실제 우주선 관측 자료가 아닙니다.':'회전계에서 L1–L5는 z=0에 있는 고립된 점입니다. 관성계로 바꾸면 ‘고정’이 좌표계에 의존한다는 사실을 확인할 수 있습니다.';
 if(!potential&& !local)$('readout').textContent+=' 천체와 점의 표시 반지름은 가독성을 위한 기호 크기입니다.';
 projection(s,S,li,t,orbit,q,inertial,potential);return s;
}
function projection(scene,S,li,t,orbit,q,inertial,potential){const{ctx:c,w,h}=setup(map),b=scene.bound,center=scene.center,L=20,T=26,W=w-30,H=h-50,sc=Math.min(W,H)/(2*b),P=p=>[w/2+(p[0]-center[0])*sc,(h+T)/2-(p[1]-center[1])*sc];c.font='10px system-ui';c.fillStyle=dark()?'#c5d6eb':'#3e5874';c.fillText(potential?'공간 z=0 · 퍼텐셜 그래프의 정의역':`위에서 본 x–y 투영 · ${inertial?'관성계':'회전계'}`,6,14);c.save();c.beginPath();c.rect(8,22,w-16,h-40);c.clip();
 function dot(p,color,r){c.fillStyle=color;c.beginPath();c.arc(...P(p),r,0,2*pi);c.fill();}function path(a,color){c.strokeStyle=color;c.lineWidth=1.3;c.beginPath();a.forEach((p,i)=>i?c.lineTo(...P(p)):c.moveTo(...P(p)));c.stroke();}
 path([[center[0]-b,center[1],0],[center[0]+b,center[1],0]],dark()?'#53677e':'#a3b3c5');path([[center[0],center[1]-b,0],[center[0],center[1]+b,0]],dark()?'#53677e':'#a3b3c5');
 if(orbit&&!potential){path(orbit.states.filter((_,i)=>i%4===0).map(a=>inertial?M.rotate(a.slice(1,4),a[0]):a.slice(1,4)),orange);dot(inertial?M.rotate(q,t):q,orange,3.5);}
 S.points.forEach((p,i)=>dot(inertial?M.rotate(p,t):p,i===li-1?purple:green,i===li-1?4:2));c.restore();c.fillStyle=dark()?'#c5d6eb':'#3e5874';c.fillText(`가로·세로 같은 척도 · 반폭 ${num(b*S.lunit)} km`,6,h-8);
}
function render(s){const{ctx:c,w,h}=setup(cv),sc=Math.min(w-38,h-102)/(2*s.bound)*zoom,project=p=>{const v=p.map((a,i)=>a-s.center[i]),xx=Math.cos(yaw)*v[0]-Math.sin(yaw)*v[1],yy=Math.sin(yaw)*v[0]+Math.cos(yaw)*v[1],zz=Math.cos(pitch)*v[2]-Math.sin(pitch)*yy,depth=Math.sin(pitch)*v[2]+Math.cos(pitch)*yy;return[w/2+xx*sc,h*.54-zz*sc,depth];};
 const primitives=[];for(const item of s.items){if(item.kind==='line'){for(let i=0;i<item.points.length-1;i++)primitives.push({...item,projected:[project(item.points[i]),project(item.points[i+1])]});}else primitives.push({...item,projected:item.points.map(project)});}for(const p of primitives)p.depth=p.projected.reduce((a,q)=>a+q[2],0)/p.projected.length;primitives.sort((a,b)=>b.depth-a.depth);c.save();c.beginPath();c.rect(0,53,w,h-75);c.clip();
 for(const p of primitives){c.globalAlpha=p.alpha;c.strokeStyle=p.color;c.fillStyle=p.color;c.lineWidth=p.width||.5;c.beginPath();if(p.kind==='point'){c.arc(p.projected[0][0],p.projected[0][1],p.r,0,2*pi);c.fill();}else{p.projected.forEach((q,i)=>i?c.lineTo(q[0],q[1]):c.moveTo(q[0],q[1]));if(p.kind==='face'){c.closePath();c.fill();}else c.stroke();}}
 c.globalAlpha=1;for(const{p,text,color}of s.labels){const q=project(p);if(q[0]<0||q[0]>w||q[1]<55||q[1]>h-20)continue;c.font='bold 11px system-ui';c.fillStyle=color;c.fillText(text,q[0]+6,q[1]-6);}c.restore();c.fillStyle=dark()?'#dfebfb':'#29425f';c.font='bold 11px system-ui';s.head.forEach((text,i)=>c.fillText(text,8,18+17*i));c.font='10px system-ui';c.fillText(`드래그/방향키 회전 · +− 배율 ${zoom.toFixed(2)}×`,8,h-8);$('zoom-info').textContent=zoom.toFixed(2)+'×';$('progress-value').textContent=(Number($('progress').value)*100).toFixed(1)+'%';
}
function schedule(){if(!request)request=requestAnimationFrame(()=>{request=0;render(scene());});}function pause(){$('progress').dispatchEvent(new Event('input',{bubbles:true}));}
for(const el of document.querySelectorAll('.controls input,.controls select'))el.addEventListener('input',()=>{if(['system','point'].includes(el.id)){$('progress').value=0;if($('mode').value==='space'&&$('frame').value==='rotating')$('view').value=Number($('point').value)<=2?'local':'global';pause();}schedule();});
$('reset').addEventListener('click',()=>{$('system').value='sun-earth';$('point').value='2';$('view').value='local';$('mode').value='space';$('frame').value='rotating';$('progress').value=0;yaw=.5;pitch=.65;zoom=1;pause();schedule();});
$('front').addEventListener('click',()=>{yaw=0;pitch=-pi/2;pause();schedule();});$('oblique').addEventListener('click',()=>{yaw=.5;pitch=.65;pause();schedule();});
cv.addEventListener('pointerdown',e=>{drag=[e.clientX,e.clientY];cv.setPointerCapture(e.pointerId);pause();});cv.addEventListener('pointerup',()=>drag=null);cv.addEventListener('pointercancel',()=>drag=null);cv.addEventListener('pointermove',e=>{if(!drag)return;yaw+=(e.clientX-drag[0])*.009;pitch=Math.max(-1.57,Math.min(1.57,pitch+(e.clientY-drag[1])*.009));drag=[e.clientX,e.clientY];schedule();});cv.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.35,Math.min(4,zoom*Math.exp(-e.deltaY*.001)));pause();schedule();},{passive:false});
cv.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')yaw-=.1;if(e.key==='ArrowRight')yaw+=.1;if(e.key==='ArrowUp')pitch=Math.min(1.57,pitch+.1);if(e.key==='ArrowDown')pitch=Math.max(-1.57,pitch-.1);if(e.key==='+')zoom=Math.min(4,zoom*1.2);if(e.key==='-')zoom=Math.max(.35,zoom/1.2);pause();schedule();});
$('show-controls').addEventListener('click',()=>{document.body.dataset.controlsVisible='true';$('controls').scrollIntoView({block:'start'});$('back-model').focus({preventScroll:true});});$('back-model').addEventListener('click',()=>{document.body.scrollTop=0;document.body.dataset.controlsVisible='false';cv.focus({preventScroll:true});});document.body.addEventListener('scroll',()=>{if(document.body.scrollTop<20)document.body.dataset.controlsVisible='false';});new ResizeObserver(schedule).observe(cv);new ResizeObserver(schedule).observe(map);matchMedia('(prefers-color-scheme:dark)').addEventListener('change',schedule);schedule();
})();
